export enum eventEnum {
   CONVERT_CURRENCY='CONVERT_CURRENCY',
   REGISTER_CREATED = 'REGISTER_CREATED',
   LOGIN_USER='LOGIN_USER',
   REGISTER_CONVERT='REGISTER_CONVERT',
   CONVERSATION_HISTORY="CONVERSATION_HISTORY",
}
